name: 'hospital_data_platform'
version: '1.0.0'

profile: 'hospital_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# =========================
# Seeds
# =========================
seeds:
  hospital_data_platform:
    +schema: CAMADA_BRONZE
    +quote_columns: false

# =========================
# Models
# =========================
models:
  hospital_data_platform:

    camada_bronze:
      +schema: CAMADA_BRONZE
      +materialized: table

    camada_prata:
      +schema: CAMADA_PRATA
      +materialized: view

    camada_ouro:
      +schema: CAMADA_OURO
      +materialized: table